version: "3"
services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  api-server:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
    command: node index.js
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_TRACE: "true"
      WATCHTOWER_DEBUG: "true"
      WATCHTOWER_POLL_INTERVAL: 50
  mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
