version: "3"
services:
  api-server:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - ./:/app:ro
      - app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
