version: "3.4"
services:
  nginx:
    ports:
      - "4000:80"
  api-server:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - app/node_modules
    environment:
      NODE_ENV: development
      SESSION_SECRET: secret202210232cat
    command: npm run dev
