version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-server
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_USER: docker-example
      MONGO_PASSWORD: docker-example
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: docker-example
      MONGO_INITDB_ROOT_PASSWORD: docker-example
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis:7.0.5-alpine
volumes:
  mongo-db:
